# Generated by Django 3.1 on 2022-01-23 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20220123_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingaddress',
            name='country',
            field=models.CharField(blank=True, default='Turkmenistan', max_length=50, null=True),
        ),
    ]
