# Generated by Django 3.1 on 2022-01-23 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20220123_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingaddress',
            name='phone_extra',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
