# Generated by Django 3.1 on 2022-01-23 15:58

import accounts.models
from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20220123_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, default='photos/user/default.jpg', force_format='JPEG', keep_meta=True, quality=100, size=[100, 100], upload_to=accounts.models.UserProfile.image_name),
        ),
    ]
