# Generated by Django 3.1 on 2022-02-06 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20220127_1811'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('car_brand', models.CharField(max_length=30)),
                ('car_model', models.CharField(max_length=30)),
                ('car_year', models.CharField(max_length=4)),
                ('car_plate', models.CharField(max_length=15)),
                ('mobile', models.CharField(max_length=30)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.vendor')),
            ],
        ),
    ]
