# Generated by Django 3.1 on 2022-02-28 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_auto_20220225_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
