# Generated by Django 3.1 on 2022-11-15 16:46

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_auto_20220302_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='photos/user/default.jpg', upload_to=accounts.models.UserProfile.image_name),
        ),
    ]
