# Generated by Django 3.1 on 2022-01-29 03:40

from django.db import migrations
import django_resized.forms
import store.models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_auto_20220129_0839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='JPEG', keep_meta=True, quality=100, size=[300, 300], upload_to=store.models.Product.medium_image_name),
        ),
    ]
