# Generated by Django 3.1 on 2022-02-14 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_driver'),
        ('store', '0018_currency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currency',
            name='usdequivalent',
        ),
        migrations.RemoveField(
            model_name='currency',
            name='vendor',
        ),
        migrations.AddField(
            model_name='currency',
            name='code',
            field=models.CharField(default=1, max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='currency',
            name='num',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='price_are_in',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.currency'),
        ),
        migrations.AlterField(
            model_name='currency',
            name='currency',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='CurrencyRates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usdequivalent', models.FloatField()),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.currency')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.vendor')),
            ],
        ),
    ]
