# Generated by Django 3.1 on 2022-02-21 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_product_fixed_sale_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='fixed_sale_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price_are_in',
        ),
        migrations.AddField(
            model_name='variation',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.currency'),
        ),
        migrations.AddField(
            model_name='variation',
            name='final_price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='variation',
            name='final_sale_price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='variation',
            name='fixed_sale_price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='variation',
            name='initial_price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='variation',
            name='is_fixed_sale_price',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='currencyrates',
            name='usdequivalent',
            field=models.FloatField(default=0),
        ),
    ]
