# Generated by Django 3.1 on 2022-02-21 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_auto_20220221_1334'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variation',
            name='final_sale_price',
        ),
        migrations.RemoveField(
            model_name='variation',
            name='fixed_sale_price',
        ),
        migrations.RemoveField(
            model_name='variation',
            name='initial_price',
        ),
        migrations.RemoveField(
            model_name='variation',
            name='is_fixed_sale_price',
        ),
        migrations.AddField(
            model_name='variation',
            name='final_tmt_price',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='variation',
            name='final_price',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
