# Generated by Django 3.1 on 2022-02-21 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0023_auto_20220221_1405'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UnitPriceCalculator',
            new_name='OtherExpense',
        ),
    ]
