# Generated by Django 3.1 on 2022-02-28 04:51

from django.db import migrations
import django_resized.forms
import store.models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0028_auto_20220226_0826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, default='photos/products/default.jpg', force_format='JPEG', keep_meta=True, null=True, quality=100, size=[500, 500], upload_to=store.models.Product.medium_image_name),
        ),
    ]
