# Generated by Django 3.1 on 2022-03-02 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0031_variation_sku'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_date']},
        ),
    ]
