# Generated by Django 3.1 on 2022-03-02 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0033_auto_20220302_1634'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='variation',
            name='single_variation',
        ),
        migrations.RemoveField(
            model_name='variation',
            name='owner',
        ),
        migrations.AddConstraint(
            model_name='variation',
            constraint=models.UniqueConstraint(fields=('product', 'color', 'size'), name='single_variation'),
        ),
    ]
