# Generated by Django 3.1 on 2022-03-03 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0035_auto_20220303_1457'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='highest_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='lowest_price',
        ),
    ]
