# Generated by Django 3.1 on 2022-03-04 13:32

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0005_auto_20220303_1645'),
        ('store', '0037_auto_20220303_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='category.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='highest_price',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_available',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='lowest_price',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
