# Generated by Django 3.1 on 2022-03-18 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0038_auto_20220304_1832'),
    ]

    operations = [
        migrations.AddField(
            model_name='variation',
            name='barcode',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='variation',
            name='is_physical',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='variation',
            name='location',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='variation',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
