# Generated by Django 3.1 on 2022-05-13 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0040_auto_20220318_1007'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='items_in_package',
            field=models.IntegerField(default=1),
        ),
    ]
