# Generated by Django 3.1 on 2022-05-16 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0042_auto_20220513_0939'),
    ]

    operations = [
        migrations.AddField(
            model_name='variation',
            name='min_order',
            field=models.IntegerField(default=1),
        ),
    ]
