branch-defaults:
  main:
    environment: sargajak-dev-env
    group_suffix: null
global:
  application_name: sargajak
  branch: null
  default_ec2_keyname: sargajakkeypair
  default_platform: Python 3.7
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
