# Generated by Django 3.1 on 2022-02-14 06:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('carts', '0003_auto_20220214_1052'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='cartdelivery',
            name='cart_vendor',
        ),
        migrations.AddField(
            model_name='cartdelivery',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cartdelivery',
            name='cart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='carts.cart'),
        ),
        migrations.AddConstraint(
            model_name='cartdelivery',
            constraint=models.UniqueConstraint(fields=('cart', 'user', 'vendor'), name='cart_vendor'),
        ),
    ]
