# Generated by Django 3.1 on 2022-02-14 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0004_auto_20220214_1159'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CartDelivery',
        ),
    ]
