# Generated by Django 3.1 on 2022-01-23 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20220123_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingaddress',
            name='address_line_2',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='billingaddress',
            name='phone_extra',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='billingaddress',
            name='state',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
