# Generated by Django 3.1 on 2022-01-27 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20220126_1956'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='slug',
            field=models.SlugField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vendor',
            name='official_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
