# Generated by Django 3.1 on 2022-11-15 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0006_auto_20220304_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, default='photos/categories/default.jpg', null=True, upload_to='photos/categories'),
        ),
    ]
