# Generated by Django 3.1 on 2022-03-03 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_auto_20220302_2310'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Genre',
        ),
    ]
