# Generated by Django 3.1 on 2022-03-04 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0005_auto_20220303_1645'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='category',
            name='category-parent',
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(fields=('parent', 'slug'), name='parentslug'),
        ),
    ]
