# Generated by Django 3.1 on 2022-02-21 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0024_auto_20220221_1541'),
    ]

    operations = [
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('increase_type', models.CharField(choices=[('percentage', '%'), ('fixed', 'Fixed')], default='percentage', max_length=20)),
                ('increase_amount', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='MoneyTransfer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('increase_type', models.CharField(choices=[('percentage', '%'), ('fixed', 'Fixed')], default='percentage', max_length=20)),
                ('increase_amount', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('increase_type', models.CharField(choices=[('percentage', '%'), ('fixed', 'Fixed')], default='percentage', max_length=20)),
                ('increase_amount', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('increase_type', models.CharField(choices=[('percentage', '%'), ('fixed', 'Fixed')], default='percentage', max_length=20)),
                ('increase_amount', models.FloatField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='variation',
            name='income',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.income'),
        ),
        migrations.AddField(
            model_name='variation',
            name='money_transfer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.moneytransfer'),
        ),
        migrations.AddField(
            model_name='variation',
            name='tax',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.tax'),
        ),
        migrations.AddField(
            model_name='variation',
            name='transport_fee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.transport'),
        ),
    ]
