# Generated by Django 3.1 on 2022-02-23 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0025_auto_20220221_1559'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variation',
            old_name='price',
            new_name='initial_price',
        ),
        migrations.RenameField(
            model_name='variation',
            old_name='final_tmt_price',
            new_name='sale_price',
        ),
        migrations.RemoveField(
            model_name='variation',
            name='income',
        ),
        migrations.RemoveField(
            model_name='variation',
            name='money_transfer',
        ),
        migrations.RemoveField(
            model_name='variation',
            name='tax',
        ),
        migrations.RemoveField(
            model_name='variation',
            name='transport_fee',
        ),
        migrations.AddField(
            model_name='variation',
            name='expense_fixed',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='variation',
            name='expense_percentage',
            field=models.FloatField(default=0),
        ),
    ]
