# Generated by Django 3.1 on 2022-02-26 03:26

from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms
import store.models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
        ('store', '0027_auto_20220223_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='variation',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, null=True, quality=100, size=[500, 500], upload_to=store.models.Variation.medium_image_name),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='category.category'),
        ),
    ]
