# Generated by Django 3.1 on 2022-03-02 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0030_auto_20220302_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='variation',
            name='sku',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
