# Generated by Django 3.1 on 2022-03-18 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0039_auto_20220318_1001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variation',
            name='is_physical',
        ),
        migrations.RemoveField(
            model_name='variation',
            name='location',
        ),
        migrations.RemoveField(
            model_name='variation',
            name='weight',
        ),
        migrations.AddField(
            model_name='product',
            name='is_physical',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='location',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
