# Generated by Django 3.1 on 2022-11-15 16:46

from django.db import migrations, models
import store.models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0044_auto_20220516_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='photos/products/default.jpg', null=True, upload_to=store.models.Product.medium_image_name),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_small',
            field=models.ImageField(blank=True, null=True, upload_to=store.models.Product.small_image_name),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=store.models.Product.thumb_image_name),
        ),
        migrations.AlterField(
            model_name='variation',
            name='expense_fixed',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='variation',
            name='expense_percentage',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='variation',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=store.models.Variation.medium_image_name),
        ),
        migrations.AlterField(
            model_name='variation',
            name='initial_price',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='variation',
            name='min_order',
            field=models.IntegerField(blank=True, default=1),
        ),
    ]
