# Generated by Django 3.1 on 2022-02-06 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20220127_1811'),
        ('orders', '0003_sale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordersales', to='orders.order'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='vendor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendorsales', to='accounts.vendor'),
        ),
    ]
