# Generated by Django 3.1 on 2022-02-06 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20220206_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='status',
            field=models.CharField(choices=[(1, 'New'), (2, 'On Delivery'), (3, 'Delivered and Paid'), (4, 'Cancelled')], default=1, max_length=1),
        ),
    ]
