# Generated by Django 3.1 on 2022-02-11 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_city_delivery'),
    ]

    operations = [
    ]
