# Generated by Django 3.1 on 2022-02-14 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_driver'),
        ('orders', '0011_auto_20220214_0946'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sale',
            new_name='OrderDelivery',
        ),
    ]
