# Generated by Django 3.1 on 2022-02-14 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_auto_20220214_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdelivery',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ordersales', to='orders.order'),
        ),
    ]
