# Generated by Django 3.1 on 2022-04-17 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0019_auto_20220417_1345'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='total',
            new_name='grand_total',
        ),
    ]
