# Generated by Django 3.1 on 2022-02-06 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20220206_1332'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='is_delivered',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='is_paid',
        ),
        migrations.AddField(
            model_name='sale',
            name='status',
            field=models.CharField(choices=[(1, 'New'), (2, 'On Delivery'), (3, 'Delivered and Paid'), (4, 'Cancelled')], default='New', max_length=50),
        ),
    ]
