# Generated by Django 3.1 on 2022-02-14 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_auto_20220211_2029'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='fee',
            field=models.FloatField(default=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='delivery',
            name='free_delivery_limit',
            field=models.FloatField(default=200),
            preserve_default=False,
        ),
    ]
