# Generated by Django 3.1 on 2022-03-18 05:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_order_channel'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_number_vendor',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
    ]
