# Generated by Django 3.1 on 2022-05-13 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0022_auto_20220424_1827'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='package_price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='product_price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
